/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cipn.exporter.ui;

import cipn.exporter.controller.ConfigController;
import cipn.exporter.controller.ExportController;
import cipn.exporter.controller.SearchController;
import cipn.exporter.util.ConfigUtil;
import cipn.exporter.util.DBUtil;
import com.hosos.comp.table.obj.TableComplexDataSource;
import com.hosos.comp.table.renderer.TableAligment;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sompr
 */
public class MainFrame extends javax.swing.JFrame {

    private final ConfigController configController = new ConfigController();
    private final SearchController searchController = new SearchController();
    private final ExportController exportController = new ExportController();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        table.initTable(new String[]{"HN", "AN", "ชื่อ-สกุล", "Invoice No.", "Amt.", "วันที่เข้ารับบริการ"
        }, true, true, false);

        table.setColumnMinWidth(2, 80);
        table.setColumnMaxWidth(2, 80);
        table.setColumnCellRenderer(2, TableAligment.setAligment(TableAligment.CENTER));
        table.setColumnMinWidth(3, 80);
        table.setColumnMaxWidth(3, 80);
        table.setColumnCellRenderer(3, TableAligment.setAligment(TableAligment.CENTER));
        table.setColumnMinWidth(5, 130);
        table.setColumnMaxWidth(5, 130);
        table.setColumnCellRenderer(5, TableAligment.setAligment(TableAligment.CENTER));
        table.setColumnMinWidth(6, 80);
        table.setColumnMaxWidth(6, 80);
        table.setColumnCellRenderer(6, TableAligment.setAligment(TableAligment.RIGHT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHn = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAn = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcStart = new com.hosos.comp.jcalendar.JDateChooser();
        dcEnd = new com.hosos.comp.jcalendar.JDateChooser();
        btnConfig = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        table = new com.hosos.comp.table.TableComplex();
        jPanel5 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("เบิกตรงกรมบัญชีกลาง (ผู้ป่วยใน)");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ค้นหาข้อมูล"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setText("HN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("ชื่อ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel3.setText("นามสกุล");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtHn.setFont(txtHn.getFont());
        txtHn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(txtHn, gridBagConstraints);

        txtFirstname.setFont(txtFirstname.getFont());
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(txtFirstname, gridBagConstraints);

        txtLastname.setFont(txtLastname.getFont());
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(txtLastname, gridBagConstraints);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel6.setText("AN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(jLabel6, gridBagConstraints);

        txtAn.setFont(txtAn.getFont());
        txtAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel3.add(txtAn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel4.setText("ตั้งแต่");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel5.setText("ถึง");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(jLabel5, gridBagConstraints);

        dcStart.setFont(dcStart.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(dcStart, gridBagConstraints);

        dcEnd.setFont(dcEnd.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel4.add(dcEnd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jPanel4, gridBagConstraints);

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cipn/exporter/image/icon-setting.png"))); // NOI18N
        btnConfig.setToolTipText("ตั้งค่าการเชื่อมต่อฐานข้อมูล");
        btnConfig.setMaximumSize(new java.awt.Dimension(22, 22));
        btnConfig.setMinimumSize(new java.awt.Dimension(22, 22));
        btnConfig.setPreferredSize(new java.awt.Dimension(22, 22));
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(btnConfig, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        btnExport.setBackground(new java.awt.Color(0, 102, 204));
        btnExport.setFont(btnExport.getFont());
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("ส่งออกรายการที่เลือก");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel6.add(btnExport, gridBagConstraints);

        btnSearch.setBackground(new java.awt.Color(0, 102, 204));
        btnSearch.setFont(btnSearch.getFont());
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("ค้นหา");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel6.add(btnSearch, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel1.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("ข้อมูลเบิกจ่าย"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        table.setFont(table.getFont());
        table.getTable().setRowHeight(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(table, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        lblStatus.setText("กำลังส่งออก: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel5.add(lblStatus, gridBagConstraints);

        lblCount.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel5.add(lblCount, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHnActionPerformed
        this.onClickedSearch();
    }//GEN-LAST:event_txtHnActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        this.onClickedSearch();
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        this.onClickedSearch();
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        this.onClickedSearch();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        this.onClickedExport();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        this.onClickedConfig();
    }//GEN-LAST:event_btnConfigActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.handleClosingApp();
    }//GEN-LAST:event_formWindowClosing

    private void txtAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnActionPerformed
        this.onClickedSearch();
    }//GEN-LAST:event_txtAnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnSearch;
    private com.hosos.comp.jcalendar.JDateChooser dcEnd;
    private com.hosos.comp.jcalendar.JDateChooser dcStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblStatus;
    private com.hosos.comp.table.TableComplex table;
    private javax.swing.JTextField txtAn;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtHn;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables

    private void onClickedSearch() {
        if (!checkConfig()) {
            return;
        }
        // parameters
        String hn = txtHn.getText().trim();
        String an = txtAn.getText().trim();
        String firstname = txtFirstname.getText().trim();
        String lastname = txtLastname.getText().trim();
        Date startDate = dcStart.getDate();
        Date endDate = dcEnd.getDate();

        table.clearTable();
        btnSearch.setEnabled(false);

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    List<TableComplexDataSource> ds = searchController.handleSearch(hn, an, firstname, lastname, startDate, endDate);
                    table.setComplexDatasource(ds);
                    btnSearch.setEnabled(true);
                } catch (Exception ex) {
                    if (ex.getMessage().equals("No HIS")) {
                        JOptionPane.showMessageDialog(null, "ไม่พบข้อมูลการตั้งค่าชื่อระบบ", "เตือน", JOptionPane.WARNING_MESSAGE);
                    } else if (ex.getMessage().equals("No database config.")) {
                        JOptionPane.showMessageDialog(null, "ไม่พบข้อมูลการตั้งค่าการเชื่อมต่อฐานข้อมูล", "เตือน", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        });
        t.start();

    }

    private boolean checkConfig() {
        if (ConfigUtil.isValide()) {
            return true;
        }

        JOptionPane.showMessageDialog(this, "ตรวจสอบการตั้งค่า", "เตือน", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    private int countTask = 0;

    private void onClickedExport() {
        if (!checkConfig()) {
            return;
        }
        List<Object> checkedIds = table.getCheckedIds();
        if (checkedIds.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ต้องรายการเบิกจ่ายอย่างน้อย 1 รายการ", "เตือน", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (countTask > 0) {
            int ret = JOptionPane.showConfirmDialog(this, "ระบบกำลังส่งออกรายงานอยู่ ยืนยันการส่งใหม่ หรือไม่", "ยืนยันการส่งใหม่", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.NO_OPTION) {
                return;
            }
        }

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                lblCount.setText(String.valueOf(++countTask));
                exportController.handleExport(checkedIds);
                lblCount.setText(String.valueOf(--countTask));
            }
        });
        t.start();
    }

    private void onClickedConfig() {
        configController.handleConfig(this);
    }

    private void handleClosingApp() {
        int ans = JOptionPane.showConfirmDialog(this, "ต้องการออกจากโปรแกรม หรือไม่", "ยืนยัน", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (ans != JOptionPane.YES_OPTION) {
            return;
        }

        DBUtil.getInstance().closeConnection();
    }

    public void setVersion(String version) {
        this.setTitle(this.getTitle() + " Version " + version);
    }

}
